website=str(input('website = '))
# website = 'weiyin.github.io.tbs'
print("%.3s" % website)
print("%s" % website)
print("%.*s" % (4, website))
print("%7.3s" % website)
print("%-7.3s" % website)
print("%12.3s" % website)
print("%.12s" % website)
print("1:%s" % website.split(".")[0])
print("2:%s" % website.split(".")[1])
print("3:%s" % website.split(".")[2])
print("4:%s" % website.split(".")[3])
print("5:%s" % website.split(".", -1))
print("6:%s" % website.split(".", 0))
print("7:%s" % website.split(".", 1))
print("8:%s" % website.split(".", 2))
print("9:%s" % website.split(".", 3))
